### ISSUE TITLE
View-only sharable link not functional

### ISSUE THREAD

**Issue by zeigerpuppy** [ndarilek/dokuwiki-sandstorm#8] opened 2016-11-09 13:27 UTC
An anonymous user browsing to a shareable sandstorm link cannot access the site.

They see a "Permission Denied" error

```
No ACL setup yet! Denying access to everyone.

Permission Denied
Sorry, you don't have enough rights to continue.
```

**Comment by ndarilek** [comment] 2016-11-09 23:54
Thanks for reporting. Closing as a duplicate of #3. Please track/submit changes there.

**Closed as completed by ndarilek** 2016-11-09 23:54 UTC
